Repository GDG-on-Campus-KNU/4th-SC-Team-6-BE, pull requests merged in 2025-05, with the labels that each got.

#22 Feature/issue#15: blue/green 배포 구현 및 도커파일 추가
  .github/workflows/cd.yaml
  .github/workflows/ci.yml
  .github/workflows/test.yaml
  .gitignore
  Dockerfile
  k8s/blue/deploy.yaml
  k8s/blue/kustomization.yaml
  k8s/green/deploy.yaml
  k8s/green/kustomization.yaml
  k8s/service.yaml
Labels: ⚙ Setting, 🌏 Deploy

#20 chore(githubaction)-환경변수(google_api_key)-추가
  .github/workflows/test.yaml
Labels: ⚙ Setting, ✅ Test

#19 Update ci.yml to add google api key in github action
  .github/workflows/ci.yml
Labels: ⚙ Setting, 🌏 Deploy

#26 Feature/issue#23: Music 도메인 추가
  src/main/java/com/feelody/feelody_backend/controller/MusicController.java
  src/main/java/com/feelody/feelody_backend/entity/Music.java
  src/main/java/com/feelody/feelody_backend/repository/MusicRepository.java
  src/main/java/com/feelody/feelody_backend/service/MusicService.java
Labels: ✨ Feature

#31 fix: outputs 위치를 정확하게 들여쓰기 수정
  .github/workflows/ci.yml
Labels: 🌏 Deploy, 🐞 Bug

#30 Feature/issue#29
  build.gradle
  src/main/java/com/feelody/feelody_backend/controller/BpmController.java
  src/main/java/com/feelody/feelody_backend/global/config/WebSocketConfig.java
Labels: ✨ Feature

#34 feat: cors 요청 허용 설정
  src/main/java/com/feelody/feelody_backend/global/config/WebConfig.java
Labels: ⚙ Setting, ✨ Feature, 🌏 Deploy
